#!/bin/bash
export QTDIR=/path_to_qt/qt
export PATH=$QTDIR/bin:$PATH
export DYLD_LIBRARY_PATH =$QTDIR/lib:$LD_LIBRARY_PATH
export BOOST_INCLUDE=path_to_boost_include/
export BOOST_BUILD_PATH=path_to_boost_build/build/v2
export COLORLIBBASE_LIB=path_to/ColorLib_cpp/
path_to_bjam/bjam architecture=x86 address-model=32 macosx-version=10.6 $*